# === Files ===

IgnorePath '/.snapshots/*' # BTRFS snapshots
IgnorePath '/var/tmp/*'
IgnorePath '/var/lib/*'
IgnorePath '/var/log/*'
IgnorePath '/var/spool/*'
IgnorePath '/boot/*'
IgnorePath '/bin/*' # Only edited files are Ruby's
IgnorePath '/usr/bin/*' # Same "
IgnorePath '/var/.updated'
IgnorePath '/etc/.updated'
IgnorePath '/srv/*'

IgnorePath '/etc/grub.d/backup/*'
IgnorePath '/etc/xml/catalog' # http://xmlsoft.org/catalog.html

# CUPS files, which seem to have printer configuration but change _quite_ often
IgnorePath '/etc/cups/classes.conf'
IgnorePath '/etc/cups/classes.conf.O'
IgnorePath '/etc/cups/printers.conf'
IgnorePath '/etc/cups/printers.conf.O'
IgnorePath '/etc/cups/subscriptions.conf'
IgnorePath '/etc/cups/subscriptions.conf.O'

# Recreated files
IgnorePath '/usr/lib/ruby/gems/*'
IgnorePath '/usr/lib/node_modules/*'
IgnorePath '/usr/lib/virtualbox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack/*' # VBox extension pack from AUR
IgnorePath '/usr/local/bin/idea' # IntelliJ Idea; created automatically
IgnorePath '/usr/lib/vlc/plugins/plugins.dat' # VLC plugins
IgnorePath '/usr/lib/modules/*' # Kernel modules (rebuilt)
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/pacman.d/mirrorlist' # Regenerated by reflector
IgnorePath '/etc/printcap'
IgnorePath '/etc/resolv.conf'
IgnorePath '/etc/resolv.conf.bak'
# info
IgnorePath '/usr/share/info/dir'

# udev
IgnorePath '/etc/udev/hwdb.bin' # https://www.freedesktop.org/software/systemd/man/hwdb.html
# locale
IgnorePath '/usr/lib/locale/locale-archive'
# Gnome
IgnorePath '/usr/lib/gio/modules/giomodule.cache'
IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled' # https://developer.gnome.org/gio/stable/glib-compile-schemas.html

# mimeinfo
IgnorePath '/usr/local/share/applications/mimeinfo.cache'
IgnorePath '/usr/share/applications/mimeinfo.cache'

# MIME database
IgnorePath '/usr/share/mime/aliases' # MIME aliases
IgnorePath '/usr/share/mime/*.xml' # Localizations
IgnorePath '/usr/share/mime/generic-icons'
IgnorePath '/usr/share/mime/globs' # File extensions
IgnorePath '/usr/share/mime/globs2' # Weighted file extensions?
IgnorePath '/usr/share/mime/icons'
IgnorePath '/usr/share/mime/magic' # Binary magic database
IgnorePath '/usr/share/mime/mime.cache' # Binary
IgnorePath '/usr/share/mime/subclasses'
IgnorePath '/usr/share/mime/treemagic' # Directory magic
IgnorePath '/usr/share/mime/types'
IgnorePath '/usr/share/mime/version'
IgnorePath '/usr/share/mime/XMLnamespaces'
IgnorePath '/usr/share/mime/packages/kde.xml.bkp'

# User accounts
IgnorePath '/etc/group-' # 
IgnorePath '/etc/gshadow' # 
IgnorePath '/etc/gshadow-' # 
IgnorePath '/etc/passwd-' # 
IgnorePath '/etc/shadow' # 
IgnorePath '/etc/shadow-' # 

# Certificates

IgnorePath '/etc/ca-certificates/extracted' # WATCH ME
IgnorePath '/etc/ssl/certs' # Symlinks to the above
IgnorePath '/usr/share/.mono/certs/Trust/*'

# Development - Languages - Python

IgnorePath '/usr/lib/python2.7/site-packages/*.pyc'
IgnorePath '/usr/lib/python3.5/site-packages/*.pyc'
IgnorePath '/usr/share/gcc-*/python/*/__pycache__/*.pyc'
IgnorePath '/usr/share/gdb/python/*/__pycache__/*.pyc'
IgnorePath '/usr/share/nautilus-python/extensions/*.pyc'

# Desktop - Fonts

IgnorePath '/usr/share/fonts/misc/fonts.dir'
IgnorePath '/usr/share/fonts/misc/fonts.scale'
IgnorePath '/usr/share/fonts/OTF/fonts.dir'
IgnorePath '/usr/share/fonts/OTF/fonts.scale'
IgnorePath '/usr/share/fonts/ttf-brill/fonts.dir'
IgnorePath '/usr/share/fonts/ttf-brill/fonts.scale'
IgnorePath '/usr/share/fonts/TTF/fonts.dir'
IgnorePath '/usr/share/fonts/TTF/fonts.scale'
IgnorePath '/usr/share/fonts/Type1/fonts.dir'
IgnorePath '/usr/share/fonts/Type1/fonts.scale'

# Icons
IgnorePath '/usr/share/icons/*/icon-theme.cache'


# Development - TeX [for D]

IgnorePath '/etc/texmf/ls-R' # "filename database for kpathsea"
IgnorePath '/etc/texmf/web2c/updmap.cfg' # "The updmap.cfg in the TEXMFDIST tree is generated by tlmgr by concatenating updmap-hdr.cfg with the updmap.cfg files in this tree."
IgnorePath '/usr/share/texmf-dist/ls-R'

# GTK
IgnorePath '/etc/gtk-2.0/gdk-pixbuf.loaders'
IgnorePath '/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders.cache'
IgnorePath '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'

IgnorePath '/usr/lib32/gtk-2.0/2.10.0/immodules.cache'
IgnorePath '/usr/lib/gtk-2.0/2.10.0/immodules.cache'
IgnorePath '/usr/lib/gtk-3.0/3.0.0/immodules.cache'

# LVM
IgnorePath '/etc/lvm/cache/.cache' # "The vgscan command scans all supported disk devices in the system looking for LVM physical volumes and volume groups. This builds the LVM cache in the /etc/lvm/.cache file, which maintains a listing of current LVM devices."

IgnorePath '/usr/share/perl5/vendor_perl/XML/SAX/ParserDetails.ini'

# === Packages! ===

# Windows 10 fonts, because they can't be automatically compiled
IgnorePackage --foreign ttf-ms-win10 # Microsoft Windows 10 TrueType fonts
IgnorePackage --foreign ttf-ms-win10-japanese # Microsoft Windows 10 Japanese TrueType fonts
IgnorePackage --foreign ttf-ms-win10-korean # Microsoft Windows 10 Korean TrueType fonts
IgnorePackage --foreign ttf-ms-win10-other # Microsoft Windows 10 Other TrueType fonts
IgnorePackage --foreign ttf-ms-win10-sea # Microsoft Windows 10 Southeast Asian TrueType fonts
IgnorePackage --foreign ttf-ms-win10-thai # Microsoft Windows 10 Thai TrueType fonts
IgnorePackage --foreign ttf-ms-win10-zh_cn # Microsoft Windows 10 Simplified Chinese TrueType fonts
IgnorePackage --foreign ttf-ms-win10-zh_tw # Microsoft Windows 10 Traditional Chinese TrueType fonts
